# Uncomment the next line to define a global platform for your project
 source 'https://github.com/CocoaPods/Specs.git'
 platform :ios, '9.0'

target 'SimpleAccountBook' do
pod 'JTAppleCalendar', '~> 7.0'
pod ’Firebase/Database'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Charts'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleAccountBook

end
